### ISSUE TITLE
The reference assemblies for framework ".NETFramework,Version=v4.8" were not found

### ISSUE THREAD

**Issue by codemaker** [cheenamalhotra/sqlclient-akv-example#1]
I get the below error when building this solution.

> MSB3644	The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	TestAzureKeyVaultProvider

**Comment by cheenamalhotra** [comment]
That comes because I also target .NET Framework 4.8 in my project.
You can either remove `net48` from  TargetFrameworks or install .NET Framework 4.8.

**Comment by codemaker** [comment]
I am able to debug but now I don't get the call back KeyVaultAuthenticationCallback

The below method is not hitting

      public static async Task<string> KeyVaultAuthenticationCallback(string authority, string resource, string scope)
        {
            return await Task.Run(() => new ManagedIdentityCredential().GetToken(new TokenRequestContext(new string[] { "https://vault.azure.net/.default" })).Token);
        
        }

I basically want to understand how does the application know which registered "application" in AD to contact and get access to key vault? Please help. I don't get any good article

**Comment by codemaker** [comment]
Thanks, it's work fine in Visual Studio 2019
